import './globals.scss';
import './Component/colors.scss';
import { Inter } from 'next/font/google';
import Footer from './Component/Footer';
import Navbar from './Component/Navbar';
import { Providers } from './Component/Providers';

// import styles from './page.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <div className="herosection">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
