import './globals.css';
import './Component/colors.scss';
import { Inter } from 'next/font/google';
import FooterUi from './Component/FooterUi';
import NavbarUi from './Component/NavbarUi';
import { Providers } from './Component/Providers';

// import styles from './page.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavbarUi />

          <div className="herosection">{children}</div>

          <FooterUi />
        </Providers>
      </body>
    </html>
  );
}
